#define MI_ERROR_CODES

#define MI_SHADER_COMPILE_ERROR_CODE    "MI::ERROR::SHADER_COMPILE_STATUS: "
#define MI_FREE_TYPE_ERROR_CODE         "MI::ERROR::FREE_TYPE: "
#define MI_FRAMEBUFFER_ERROR_CODE       "MI::ERROR::FRAMEBUFFER: "